excluded:
  - .build

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

disabled_rules:
  - multiple_closures_with_trailing_closure
  - vertical_parameter_alignment_on_call
  - void_return

identifier_name:
  excluded:
    - id

type_name:
  excluded:
    - ID

function_body_length: 50

line_length: 200

file_length:
    warning: 500
    error: 1000

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 10

large_tuple:
  warning: 6
  error: 10

cyclomatic_complexity:
  ignores_case_statements: true
